import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Ritual } from './ritual.entity';

const RITUALS_SEED = [
  // ============================
  // WEDDING
  // ============================
  { name: 'Roka Ceremony', localName: 'Roka', eventType: 'wedding', description: 'The official announcement of the engagement where both families meet and agree to the union.', significance: 'Marks the beginning of the wedding journey. After Roka, the boy and girl are officially considered engaged.', procedure: 'Both families meet at a mutually agreed venue. Gifts are exchanged. Priest chants mantras. Sweets distributed.', requiredItems: ['Sweets', 'Dry fruits', 'Gifts', 'Flowers'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Sagai / Ring Ceremony', localName: 'Sagai', eventType: 'wedding', description: 'The formal engagement where rings are exchanged between the bride and groom.', significance: 'Symbolizes the formal commitment between the two individuals and their families.', procedure: 'The couple exchanges rings in the presence of family and friends. Priest blesses the union. Photos taken.', requiredItems: ['Engagement rings', 'Flowers', 'Sweets', 'Puja thali'], dayNumber: 1, timing: 'evening', isStateSpecific: false },
  { name: 'Haldi Ceremony', localName: 'Haldi / Pithi', eventType: 'wedding', description: 'Turmeric paste is applied to the bride and groom separately at their respective homes.', significance: 'Turmeric is antiseptic and auspicious. It cleanses the body and gives a natural glow before the wedding.', procedure: 'Female relatives apply turmeric paste mixed with sandalwood, rose water to the bride/groom. Songs are sung. After applying, the person is bathed.', requiredItems: ['Turmeric', 'Sandalwood powder', 'Rose water', 'Mustard oil', 'Flowers'], dayNumber: 2, timing: 'morning', isStateSpecific: false },
  { name: 'Mehendi Ceremony', localName: 'Mehendi / Henna Night', eventType: 'wedding', description: 'Intricate henna designs are applied on the hands and feet of the bride.', significance: 'Mehndi symbolizes love, prosperity and the bond between husband and wife. Darker the color, stronger the love.', procedure: 'A professional mehndi artist applies intricate designs. Songs are sung. Groom\'s name hidden in the design — he must find it on the wedding night.', requiredItems: ['Henna paste', 'Lemon juice', 'Sugar', 'Essential oils', 'Music'], dayNumber: 2, timing: 'evening', isStateSpecific: false },
  { name: 'Sangeet Ceremony', localName: 'Sangeet', eventType: 'wedding', description: 'A musical evening where both families come together to sing, dance and celebrate.', significance: 'Brings both families closer. A celebration of joy before the serious rituals of the wedding day.', procedure: 'Choreographed dance performances by family members. Live music or DJ. Games between families. Dinner/snacks served.', requiredItems: ['Music system', 'Dance floor', 'Decorations', 'Costumes', 'Food'], dayNumber: 2, timing: 'evening', isStateSpecific: false },
  { name: 'Baraat (Groom\'s Procession)', localName: 'Baraat / Barat', eventType: 'wedding', description: 'The groom arrives at the wedding venue with family and friends in a grand procession.', significance: 'Symbolizes the groom\'s journey to claim his bride. A grand celebration of his arrival.', procedure: 'Groom arrives on horse or in decorated car. Dhol players lead. Family dances. Bride\'s family waits to welcome at the gate with aarti.', requiredItems: ['Decorated horse/car', 'Dhol', 'Flowers', 'Sehra (groom\'s veil)', 'Lights/torch bearers'], dayNumber: 3, timing: 'evening', isStateSpecific: false },
  { name: 'Saptapadi (Seven Vows)', localName: 'Saat Phere / Saptapadi', eventType: 'wedding', description: 'The bride and groom take seven rounds around the sacred fire, each round representing a vow.', significance: 'The most sacred part of a Hindu wedding. After the seven vows, the marriage is legally and spiritually complete.', procedure: 'Bride and groom hold a cloth between them (or groom holds bride\'s hand). They walk seven times around the Agni (fire) taking seven vows of love, loyalty, prosperity, health, children, harmony, and friendship.', requiredItems: ['Havan kund', 'Sacred fire', 'Ghee', 'Samagri', 'Cloth/dupatta'], dayNumber: 3, timing: 'morning', isStateSpecific: false },
  { name: 'Sindoor Daan', localName: 'Sindoor Daan', eventType: 'wedding', description: 'The groom applies vermilion (sindoor) in the parting of the bride\'s hair.', significance: 'After this ritual, the bride is officially a married woman. Sindoor is worn throughout marriage as a symbol of commitment.', procedure: 'After the seven pheras, groom takes sindoor and applies it in the bride\'s hair parting while priest chants mantras.', requiredItems: ['Sindoor (vermilion)', 'Small bowl', 'Flowers'], dayNumber: 3, timing: 'morning', isStateSpecific: false },
  { name: 'Mangalsutra', localName: 'Mangalsutra', eventType: 'wedding', description: 'The groom ties a sacred black and gold beaded necklace around the bride\'s neck.', significance: 'The Mangalsutra is the symbol of marriage. The black beads ward off evil eye. Wearing it means the husband is alive and well.', procedure: 'Groom ties the Mangalsutra around bride\'s neck three times while priest chants. This is done right after sindoor ceremony.', requiredItems: ['Mangalsutra', 'Gold pendant', 'Black beads'], dayNumber: 3, timing: 'morning', isStateSpecific: false },
  { name: 'Vidaai', localName: 'Vidaai / Doli', eventType: 'wedding', description: 'The emotional farewell ceremony as the bride leaves her parental home for the last time.', significance: 'One of the most emotional rituals. The bride bids goodbye to her family and begins her new life with her husband.', procedure: 'Bride throws rice over her head towards her parents\' home (for prosperity). She does not look back. She touches feet of elders. Gets into the car and leaves.', requiredItems: ['Rice', 'Flowers', 'Decorated car'], dayNumber: 3, timing: 'evening', isStateSpecific: false },
  { name: 'Griha Pravesh After Wedding', localName: 'Grihapravesh', eventType: 'wedding', description: 'The bride enters the groom\'s home for the first time with rituals.', significance: 'Welcoming the new bride (Lakshmi) into the family home. Her first step brings prosperity.', procedure: 'Bride knocks over a pot of rice with her right foot at the entrance. Mother-in-law welcomes with aarti. Bride enters with right foot first.', requiredItems: ['Rice pot', 'Alta (red dye)', 'Aarti thali', 'Flowers'], dayNumber: 4, timing: 'morning', isStateSpecific: false },

  // Rajasthan specific
  { name: 'Baan Baithna', localName: 'Baan', eventType: 'wedding', description: 'A 5-day pre-wedding ritual in Rajasthan where the bride/groom is not allowed to leave home.', significance: 'Sacred preparation period. The person is considered vulnerable to evil spirits before marriage.', procedure: 'Bride/groom sits on a wooden platform. Female relatives apply oil and turmeric daily for 5 days. Songs are sung.', requiredItems: ['Mustard oil', 'Turmeric', 'Wooden platform', 'Flowers'], dayNumber: 1, timing: 'morning', isStateSpecific: true },
  { name: 'Palla Dastoor', localName: 'Palla', eventType: 'wedding', description: 'In Rajasthan, the groom\'s turban is tied to the bride\'s dupatta, uniting them.', significance: 'Symbolizes the tying together of two lives and families forever.', procedure: 'Priest ties the groom\'s turban cloth to the bride\'s dupatta during the pheras. They remain tied throughout the ceremony.', requiredItems: ['Groom\'s turban', 'Bride\'s dupatta', 'Sacred thread'], dayNumber: 3, timing: 'morning', isStateSpecific: true },

  // ============================
  // ENGAGEMENT
  // ============================
  { name: 'Tilak Ceremony', localName: 'Tilak / Tika', eventType: 'engagement', description: 'The bride\'s family visits the groom\'s home and applies a tilak on his forehead.', significance: 'Officially marks the groom as chosen. A sign of acceptance and respect from the bride\'s family.', procedure: 'Bride\'s father or brother applies the tilak. Gifts, sweets, and dry fruits are given to the groom. Sweets distributed.', requiredItems: ['Vermilion', 'Rice', 'Flowers', 'Sweets', 'Gifts', 'Puja thali'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Ring Exchange', localName: 'Ring Ceremony', eventType: 'engagement', description: 'The couple exchanges rings in the presence of family, friends and elders.', significance: 'The ring is a circle — no beginning, no end — symbolizing eternal commitment.', procedure: 'Couple sits on stage. Boy puts ring on girl\'s right hand, girl puts ring on boy\'s right hand. Photos taken. Blessings received from elders.', requiredItems: ['Engagement rings', 'Decorated stage', 'Flowers', 'Cake'], dayNumber: 1, timing: 'evening', isStateSpecific: false },

  // ============================
  // CHILDBIRTH
  // ============================
  { name: 'Godh Bharai', localName: 'Godh Bharai / Baby Shower', eventType: 'childbirth', description: 'A baby shower ceremony for the mother-to-be, celebrated in the 7th or 9th month of pregnancy.', significance: 'Blesses the pregnant woman and the unborn child. Celebrates the journey into motherhood.', procedure: 'Woman is made to sit in the lap of a married woman (filling the lap/godh). Gifts placed in her lap. Sweets, fruits, and new clothes given. Women sing songs.', requiredItems: ['New clothes', 'Fruits', 'Sweets', 'Bangles', 'Coconut'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Naamkaran (Naming Ceremony)', localName: 'Naamkaran', eventType: 'childbirth', description: 'The official naming ceremony of the newborn, performed on the 11th or 12th day after birth.', significance: 'The name given will shape the child\'s identity. Name is chosen based on astrology and family tradition.', procedure: 'Priest performs puja. Father whispers the child\'s name in its right ear. Name announced to the gathering. Sweets distributed.', requiredItems: ['Puja items', 'Gold item for baby', 'Sweets', 'New clothes for baby'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Annaprashan (First Rice)', localName: 'Annaprashan / Mukhe Bhaat', eventType: 'childbirth', description: 'The first time solid food (rice) is fed to the baby — usually at 6 months.', significance: 'Marks the transition from milk to solid food. An important developmental milestone celebrated with family.', procedure: 'Baby is dressed in new clothes. Priest performs puja. Father or grandfather feeds the first spoon of rice kheer to the baby. Family celebrates.', requiredItems: ['Rice kheer', 'Silver spoon', 'New clothes for baby', 'Puja items'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // ============================
  // MUNDAN
  // ============================
  { name: 'Mundan Ceremony', localName: 'Mundan / Chudakarana / Baal Utaran', eventType: 'mundan', description: 'The first haircut of a child, usually performed between ages 1-3.', significance: 'Removes the hair from previous birth. Believed to promote good health, intelligence and a long life.', procedure: 'Child is brought to a temple or the ceremony is done at home. Priest chants mantras. Barber shaves the head. Hair is offered to God or river. Child is bathed.', requiredItems: ['Razor', 'Coconut', 'Flowers', 'Puja items', 'New clothes for child'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Janampatri Making', localName: 'Janampatri / Kundali', eventType: 'mundan', description: 'The child\'s birth chart (horoscope) is made by the family astrologer.', significance: 'The birth chart guides the child\'s entire life — marriage, career, education decisions all refer to it.', procedure: 'Parents visit the family astrologer with exact birth date, time, and place. Astrologer creates the Janampatri. First Mundan date is fixed based on this.', requiredItems: ['Birth details', 'Paper/notebook', 'Fee for astrologer'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // ============================
  // GRIHA PRAVESH
  // ============================
  { name: 'Vastu Puja', localName: 'Vastu Puja', eventType: 'griha-pravesh', description: 'Worship of Vastu Purusha (deity of space and direction) before entering a new home.', significance: 'Ensures positive energy flow in the home. Removes Vastu doshas and blesses it with peace and prosperity.', procedure: 'Priest draws a Vastu mandala on the floor. Nine planets and Vastu Purusha are worshipped with specific mantras. Coconut broken at the entrance.', requiredItems: ['Coconut', 'Havan kund', 'Ghee', 'Flowers', 'Navagraha items', 'Mango leaves'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Kalash Sthapana', localName: 'Kalash Sthapana', eventType: 'griha-pravesh', description: 'A sacred pot filled with water and topped with a coconut is placed at the entrance.', significance: 'The Kalash represents Goddess Lakshmi — symbolizes wealth and positive energy entering the new home.', procedure: 'Copper pot filled with holy water, mango leaves around rim, coconut on top. Red thread tied. Priest chants while establishing the Kalash.', requiredItems: ['Copper Kalash', 'Holy water', 'Mango leaves', 'Coconut', 'Red thread', 'Rice'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Griha Pravesh Havan', localName: 'Griha Havan', eventType: 'griha-pravesh', description: 'Sacred fire ritual to purify the new home and invoke divine blessings.', significance: 'Fire is the purest element. Havan smoke purifies the air and removes all negative energies.', procedure: 'Fire pit set up with specific woods. Priest chants Vedic mantras while ghee, grains, herbs are offered. Family members make offerings.', requiredItems: ['Havan kund', 'Mango wood', 'Ghee', 'Samagri', 'Camphor'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Gau Puja', localName: 'Gau Puja', eventType: 'griha-pravesh', description: 'A cow is brought to the entrance and worshipped before the family enters.', significance: 'Cow is sacred in Hinduism. Its entry into the home brings prosperity and divine blessings.', procedure: 'Cow decorated with garlands and vermilion. Owner applies tilak, offers jaggery, seeks blessings before entering.', requiredItems: ['Decorated cow', 'Garlands', 'Vermilion', 'Jaggery', 'Grass', 'Flowers'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'First Entry Ritual', localName: 'Griha Pravesh Entry', eventType: 'griha-pravesh', description: 'The formal first entry of the family into the new home with auspicious rituals.', significance: 'Sets the tone for all future life in that home. Done auspiciously to invite positivity and prosperity.', procedure: 'Wife enters first with right foot, carrying rice pot. Husband follows. Milk boiled until it overflows. Sweets distributed to all.', requiredItems: ['Rice pot', 'Milk', 'Flowers', 'Alta (red dye)', 'Sweets', 'Rangoli'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Satyanarayan Puja', localName: 'Satyanarayan Katha', eventType: 'griha-pravesh', description: 'Reading of the Satyanarayan story — a puja for Lord Vishnu on auspicious occasions.', significance: 'Performed for blessings, prosperity and fulfillment of wishes in the new home.', procedure: 'Priest reads five chapters of Satyanarayan Katha. Family listens. Prasad distributed at end.', requiredItems: ['Puja thali', 'Banana', 'Semolina', 'Milk', 'Sugar', 'Tulsi leaves'], dayNumber: 1, timing: 'evening', isStateSpecific: false },

  // ============================
  // UPANAYANA
  // ============================
  { name: 'Nandi Shraddha', localName: 'Nandi Shraddha', eventType: 'upanayana', description: 'Offering of food and prayers to ancestors before the Upanayana ceremony.', significance: 'Seeks blessings of departed ancestors for the boy starting his Vedic education.', procedure: 'Priest performs ritual with food offerings for ancestors. Family members pay respects to forefathers.', requiredItems: ['Rice', 'Sesame seeds', 'Water', 'Kusha grass', 'Flowers'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Pre-Ceremony Mundan', localName: 'Chudakarana', eventType: 'upanayana', description: 'The boy\'s head is shaved leaving a small tuft (Shikha) before the sacred thread ceremony.', significance: 'Shedding old self and preparing for a new disciplined student (Brahmacharya) life.', procedure: 'Barber shaves the head leaving a small tuft. Boy bathed and dressed in simple dhoti for the ceremony.', requiredItems: ['Razor', 'New white dhoti', 'Sandalwood paste', 'Flowers'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Yagnopavita (Sacred Thread)', localName: 'Janeu / Upanayana', eventType: 'upanayana', description: 'The sacred thread made of three cotton strands is placed over the boy\'s left shoulder.', significance: 'Three strands = duties to God, ancestors, sages. Marks the boy\'s second birth as a Dwija (twice-born).', procedure: 'Priest chants Gayatri mantra. Boy faces east. Sacred thread placed from left shoulder to right hip. Boy receives Gayatri mantra in right ear from father.', requiredItems: ['Yagnopavita', 'Havan kund', 'Ghee', 'Begging bowl', 'Deer skin mat', 'Staff'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Gayatri Mantra Initiation', localName: 'Gayatri Upadesh', eventType: 'upanayana', description: 'Father or guru whispers the sacred Gayatri Mantra into the boy\'s right ear for the first time.', significance: 'The Gayatri Mantra is the most powerful Vedic prayer — initiation into Vedic knowledge and spiritual life.', procedure: 'Father cups hands around boy\'s right ear and whispers mantra three times. Done privately away from others.', requiredItems: ['Sacred thread already worn'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Bhiksha (Symbolic Begging)', localName: 'Bhiksha', eventType: 'upanayana', description: 'The newly initiated boy goes around seeking symbolic alms from family members.', significance: 'Teaches humility. In ancient times students depended on alms. This ritual honors that tradition.', procedure: 'Boy carries cloth bag and staff. Goes to mother first, then grandmother, aunts. Each places rice with blessings.', requiredItems: ['Small cloth bag', 'Staff (danda)', 'Rice for family'], dayNumber: 1, timing: 'afternoon', isStateSpecific: false },
  { name: 'Surya Darshan', localName: 'Surya Namaskar', eventType: 'upanayana', description: 'The boy offers water to the sun for the first time after wearing the sacred thread.', significance: 'Sun is the source of all knowledge. Connects the new student with cosmic energy to begin Vedic learning.', procedure: 'Boy stands facing east. Cups water in hands and offers to the sun while chanting Gayatri mantra.', requiredItems: ['Water', 'Copper vessel', 'Open space facing east'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // ============================
  // FESTIVALS
  // ============================

  // DIWALI
  { name: 'Diwali - Lakshmi Puja', localName: 'Lakshmi Puja', eventType: 'festival', description: 'Worship of Goddess Lakshmi on Diwali night for wealth, prosperity and good fortune.', significance: 'Lakshmi enters only clean, well-lit homes. This puja invites the goddess of wealth for the year ahead.', procedure: 'Home cleaned and decorated with diyas and rangoli. Lakshmi-Ganesha idol placed on decorated platform. Puja with flowers, sweets, lamps. Firecrackers follow.', requiredItems: ['Lakshmi-Ganesha idol', 'Diyas (oil lamps)', 'Rangoli colors', 'Sweets', 'Flowers', 'Kheel-batasha', 'Incense'], dayNumber: 1, timing: 'evening', isStateSpecific: false },
  { name: 'Diwali - Dhanteras Puja', localName: 'Dhanteras', eventType: 'festival', description: 'Two days before Diwali — purchase of gold, silver or utensils and worship of Goddess Lakshmi.', significance: 'Dhanteras means 13th day of wealth. Buying metal items on this day brings prosperity.', procedure: 'Buy gold, silver or new utensils. Light 13 diyas. Worship Lakshmi and Kubera (god of wealth). Puja in evening.', requiredItems: ['Gold/silver item', '13 diyas', 'Flowers', 'Sweets', 'Puja thali'], dayNumber: 1, timing: 'evening', isStateSpecific: false },
  { name: 'Diwali - Choti Diwali', localName: 'Naraka Chaturdashi', eventType: 'festival', description: 'The day before main Diwali — celebrating Lord Krishna\'s victory over demon Narakasura.', significance: 'A day of early morning oil bath (symbolizes removing impurities) and lighting diyas at dusk.', procedure: 'Wake up early for oil bath before sunrise. Light diyas in evening. Some burst firecrackers in memory of Narakasura\'s defeat.', requiredItems: ['Sesame oil', 'Diyas', 'Flowers', 'Sweets'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // HOLI
  { name: 'Holika Dahan', localName: 'Holika Dahan', eventType: 'festival', description: 'Bonfire lit on the night before Holi to commemorate the burning of Holika.', significance: 'Victory of good over evil. Prahlad\'s devotion saved him, Holika burned despite her protective shawl.', procedure: 'Community gathers around a bonfire after sunset. Families circle it with prayers and offerings. Coconut and popcorn offered to fire.', requiredItems: ['Wood for bonfire', 'Coconut', 'Popcorn', 'Havan items', 'Flowers'], dayNumber: 1, timing: 'evening', isStateSpecific: false },
  { name: 'Holi - Rangwali Holi', localName: 'Holi / Dhulandi', eventType: 'festival', description: 'Festival of colors — people play with colored powders and water.', significance: 'Celebrates spring, love of Radha-Krishna, and victory of good over evil. All social barriers dissolve for a day.', procedure: 'People play with dry and wet colors. Water balloons and pichkaris used. Bhang thandai served. Gujiya sweets shared. Visit friends and relatives.', requiredItems: ['Dry colors (gulal)', 'Water guns (pichkari)', 'White clothes', 'Gujiya', 'Thandai', 'Flowers'], dayNumber: 2, timing: 'morning', isStateSpecific: false },
  { name: 'Lathmar Holi', localName: 'Lathmar Holi', eventType: 'festival', description: 'Unique Holi of Barsana and Nandgaon (Uttar Pradesh) where women beat men with sticks.', significance: 'Commemorates the legend of Krishna teasing Radha and the gopis who chased him away with sticks.', procedure: 'Women of Barsana welcome men from Nandgaon by beating them with sticks. Men protect themselves with shields. Everyone is drenched in colors.', requiredItems: ['Lathis (sticks)', 'Shields', 'Colors', 'Flowers'], dayNumber: 1, timing: 'morning', isStateSpecific: true },

  // NAVRATRI
  { name: 'Navratri - Kalash Sthapana', localName: 'Ghatasthapana', eventType: 'festival', description: 'Installation of a sacred pot (Kalash) on the first day of Navratri to invoke Goddess Durga.', significance: 'The Kalash is the symbol of the Goddess. Setting it up begins the nine nights of divine worship.', procedure: 'Kalash filled with water, mango leaves, coconut. Barley seeds sown in a clay pot. Priest chants mantras. Lamp lit and kept burning for 9 days.', requiredItems: ['Kalash', 'Barley seeds', 'Clay pot', 'Coconut', 'Mango leaves', 'Lamp'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
  { name: 'Navratri - Garba & Dandiya', localName: 'Garba / Dandiya Raas', eventType: 'festival', description: 'Traditional circular dance performed around a lamp or image of the Goddess.', significance: 'The circular dance represents the cycle of life. Each night devoted to a different form of Goddess Durga.', procedure: 'Participants in traditional attire dance in circles around a central lamp/deity. Dandiya uses decorated sticks. Music, singing, and community celebration.', requiredItems: ['Traditional attire (chaniya choli)', 'Dandiya sticks', 'Music system', 'Central lamp/Goddess image'], dayNumber: 1, timing: 'evening', isStateSpecific: false },
  { name: 'Navratri - Kanya Puja', localName: 'Kanjak / Kanya Puja', eventType: 'festival', description: 'On the 8th or 9th day of Navratri, young girls are worshipped as forms of the Goddess.', significance: 'Young girls represent the nine forms of Durga. Worshipping them brings divine blessings.', procedure: '9 young girls (aged 2-10) invited to the home. Their feet washed. Tilak applied. Puja performed. Halwa, puri and chana served. Girls given gifts.', requiredItems: ['9 young girls', 'Halwa', 'Puri', 'Chana', 'Gifts', 'Dupatta', 'Tilak items'], dayNumber: 9, timing: 'morning', isStateSpecific: false },

  // GANESH CHATURTHI
  { name: 'Ganesh Sthapana', localName: 'Ganesh Chaturthi', eventType: 'festival', description: 'Installation of the Ganesha idol and beginning of the 10-day festival.', significance: 'Ganesha is the remover of obstacles. His worship brings success, wisdom and new beginnings.', procedure: 'Clay Ganesha idol brought home with procession. Placed on decorated platform. Daily puja with modak and 21 durva blades. Visarjan on 10th day.', requiredItems: ['Clay Ganesha idol', 'Modak', '21 Durva grass blades', 'Red flowers', 'Coconut', 'Panchamrit'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // RAKSHA BANDHAN
  { name: 'Raksha Bandhan', localName: 'Rakhi', eventType: 'festival', description: 'Sister ties a sacred thread (Rakhi) on brother\'s wrist as a symbol of love and protection.', significance: 'The brother vows to protect his sister. An unbreakable bond of love between siblings.', procedure: 'Sister performs small puja, applies tilak, ties Rakhi on brother\'s wrist. Brother gives gifts and promises protection. Sweets exchanged.', requiredItems: ['Rakhi thread', 'Vermilion tilak', 'Rice', 'Diya', 'Sweets', 'Gifts'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // JANMASHTAMI
  { name: 'Janmashtami', localName: 'Krishna Janmashtami', eventType: 'festival', description: 'Celebration of Lord Krishna\'s birth at midnight with fasting, bhajans, and Dahi Handi.', significance: 'One of the most important Hindu festivals — birth of Lord Krishna, an avatar of Vishnu.', procedure: 'Fast during day. Krishna idol decorated with new clothes. Bhajans sung throughout the day. At midnight, conch blown, bell rung, idol given milk bath. Prasad distributed.', requiredItems: ['Krishna idol', 'Cradle (jhoola)', 'Milk', 'Curd', 'Honey', 'New clothes', 'Flowers', 'Bhajan instruments'], dayNumber: 1, timing: 'night', isStateSpecific: false },
  { name: 'Dahi Handi', localName: 'Dahi Handi / Utlotsav', eventType: 'festival', description: 'Young men form human pyramids to break a pot of curd hung high above the ground.', significance: 'Commemorates Lord Krishna\'s playful stealing of butter and curd as a child.', procedure: 'A pot filled with curd, butter and coins is hung high. Teams of young men (Govinda) form human pyramids to break it. Crowds cheer and spray water.', requiredItems: ['Large clay pot', 'Curd', 'Butter', 'Rope to hang pot', 'Water'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // MAKAR SANKRANTI
  { name: 'Makar Sankranti', localName: 'Makar Sankranti / Uttarayan / Pongal', eventType: 'festival', description: 'Festival marking the sun\'s transition into Capricorn — celebrated differently across India.', significance: 'Marks the end of winter. Celebrated as Pongal in Tamil Nadu, Lohri in Punjab, Uttarayan in Gujarat.', procedure: 'Sesame-jaggery sweets prepared and distributed. Kite flying (Gujarat). Bonfire (Punjab-Lohri). New rice pongal cooked in clay pot outdoors (Tamil Nadu). Holy bath in rivers.', requiredItems: ['Sesame seeds', 'Jaggery', 'New rice', 'Clay pot', 'Sugarcane', 'Kites (Gujarat)'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // SHYAM BABA / BHAJAN SANDHYA
  { name: 'Shyam Baba Bhajan Sandhya', localName: 'Shyam Bhajan Sandhya', eventType: 'festival', description: 'An evening of devotional songs (bhajans) dedicated to Khatu Shyam Baba, especially in Rajasthan.', significance: 'Khatu Shyam (Barbarika) is the patron deity of millions in North India. Bhajan Sandhyas are organized as vows fulfilled or blessings sought.', procedure: 'A stage is set with image/idol of Shyam Baba. Professional bhajan singers perform. Devotees sing along. Prasad distributed. Event usually all-night (jagran).', requiredItems: ['Shyam Baba image/idol', 'Decorated stage', 'Sound system', 'Flowers', 'Prasad (jalebi, rabri)', 'Dhol, harmonium'], dayNumber: 1, timing: 'evening', isStateSpecific: true },
  { name: 'Mata Ki Chowki', localName: 'Mata Ki Chowki / Jagran', eventType: 'festival', description: 'An all-night devotional gathering singing praise of Goddess Durga/Mata Vaishno Devi.', significance: 'Organized as a fulfilment of a vow (mannat) or to seek Mata\'s blessings for family welfare.', procedure: 'Home or community hall decorated with red and gold. Mata\'s image installed. Bhajan singers perform all night. Devotees take turns singing. Halwa prasad distributed at end.', requiredItems: ['Mata\'s image', 'Red cloth', 'Jyot (flame)', 'Chunri', 'Sound system', 'Halwa prasad', 'Flowers'], dayNumber: 1, timing: 'night', isStateSpecific: false },
  { name: 'Shrimad Bhagwat Katha', localName: 'Bhagwat Katha / Saptah', eventType: 'festival', description: 'A 7-day recitation of the Shrimad Bhagavat Purana by a learned Kathakar (narrator).', significance: 'Listening to the Bhagavat Katha is believed to cleanse sins, bring moksha and solve life problems.', procedure: 'A Kathakar (Pandit) narrates stories from Bhagavat Purana for 7 days. Families invite neighbors. Prasad served daily. Concludes with Maha Aarti and feast.', requiredItems: ['Decorated stage/mandap', 'Sound system', 'Bhagavat Purana book', 'Flowers', 'Prasad daily', 'Tents/seating'], dayNumber: 1, timing: 'morning', isStateSpecific: false },

  // DURGA PUJA (Bengal)
  { name: 'Durga Puja', localName: 'Durga Puja / Pujo', eventType: 'festival', description: 'The grandest festival of West Bengal — 5-day celebration of Goddess Durga\'s victory over Mahishasura.', significance: 'The most important festival for Bengalis. Goddess Durga is worshipped as the daughter returning to her maternal home.', procedure: 'Elaborate pandals (temporary temples) built with artistic themes. Priests perform daily rituals. Communities gather for puja, cultural programs. Sindoor Khela on the last day (women apply sindoor to each other). Goddess immersed in river.', requiredItems: ['Durga idol (Pratima)', 'Decorated pandal', 'Dhak (drums)', 'Flowers', 'Sindoor for final day', 'Khichdi prasad'], dayNumber: 1, timing: 'morning', isStateSpecific: true },

  // ONAM
  { name: 'Onam', localName: 'Thiruvonam', eventType: 'festival', description: 'Kerala\'s harvest festival celebrating the homecoming of King Mahabali — 10 days of celebration.', significance: 'King Mahabali was a beloved king who returns from the underworld once a year. Onam welcomes him back with grand celebrations.', procedure: 'Pookalam (flower carpet) made daily with fresh flowers. On final day: Sadhya feast (26+ dishes on banana leaf). Vallam Kali (boat races). Onakkodi (new clothes). Onathallu (martial arts).', requiredItems: ['Flowers for pookalam', 'Banana leaf', 'Sadhya dishes', 'New clothes (Onakkodi)', 'Traditional lamps'], dayNumber: 1, timing: 'morning', isStateSpecific: true },

  // PONGAL
  { name: 'Pongal', localName: 'Pongal / Thai Pongal', eventType: 'festival', description: 'Tamil Nadu\'s 4-day harvest festival thanking the Sun God, cattle, and nature.', significance: 'Gratitude to nature for a good harvest. The word "Pongal" means "to boil over" — symbolizing abundance.', procedure: 'Day 1 (Bhogi): Old things burned. Day 2 (Thai Pongal): New rice cooked outdoors in clay pot until it overflows while everyone shouts "Pongalo Pongal!". Day 3 (Mattu Pongal): Cattle worshipped. Day 4: Friends and family visited.', requiredItems: ['New rice', 'Clay pot', 'Sugarcane', 'Turmeric plant', 'Kolam (rangoli)', 'Flowers', 'Jaggery'], dayNumber: 1, timing: 'morning', isStateSpecific: true },

  // BAISAKHI
  { name: 'Baisakhi', localName: 'Vaisakhi / Baisakhi', eventType: 'festival', description: 'Punjabi harvest festival also marking the founding of the Khalsa Panth by Guru Gobind Singh in 1699.', significance: 'Double celebration — harvest of Rabi crops and the birth anniversary of the Khalsa (the Sikh community of the pure).', procedure: 'Visit Gurudwara for Ardas and langar. Community Bhangra and Gidda dance. Fairs (melas) organized. Wheat harvesting ceremonies. Amrit Sanchar ceremony for Sikhs.', requiredItems: ['Traditional Punjabi attire', 'Dhol', 'Sweets (pinni, gajak)', 'New clothes'], dayNumber: 1, timing: 'morning', isStateSpecific: true },

  // CHHATH PUJA
  { name: 'Chhath Puja', localName: 'Chhath Puja / Surya Shashti', eventType: 'festival', description: 'A 4-day festival dedicated to the Sun God (Surya) and Chhathi Maiya — major in Bihar, UP, Jharkhand.', significance: 'The only festival where devotees worship the setting sun (not just the rising sun). Gratitude for life, energy, and prosperity.', procedure: 'Day 1: Nahai Khai (ritual bath, eat once). Day 2: Kharna (fast all day, eat rice and jaggery kheer at night). Day 3: Evening arghya (offerings to setting sun at river ghat). Day 4: Morning arghya (offering to rising sun). Fast broken.', requiredItems: ['Bamboo baskets (soop)', 'Thekua (sweet)', 'Sugarcane', 'Fruits', 'Coconut', 'Diyas', 'Banana plant'], dayNumber: 1, timing: 'evening', isStateSpecific: true },

  // GURUPURAB
  { name: 'Gurupurab (Guru Nanak Jayanti)', localName: 'Gurpurab', eventType: 'festival', description: 'Birthday celebration of Guru Nanak Dev Ji — the founder of Sikhism.', significance: 'The most important day in the Sikh calendar. Celebrates the birth of the first Guru who preached equality, compassion and devotion.', procedure: 'Akhand Path (48-hour non-stop reading of Guru Granth Sahib) ends on this day. Prabhat Pheri (early morning procession) through neighborhoods. Langar (community meal) served all day. Nagarkirtan procession.', requiredItems: ['Sikh scripture (Guru Granth Sahib)', 'Langar food', 'Nishan Sahib flag', 'Musical instruments (kirtan)'], dayNumber: 1, timing: 'morning', isStateSpecific: false },
];

@Injectable()
export class RitualsService implements OnModuleInit {
  constructor(
    @InjectRepository(Ritual)
    private ritualRepo: Repository<Ritual>,
  ) {}

  async onModuleInit() {
    const count = await this.ritualRepo.count();
    if (count < 20) {
      // Clear old seed and re-seed with complete data
      await this.ritualRepo.clear();
      await this.ritualRepo.save(RITUALS_SEED);
      console.log(`✅ Rituals seeded: ${RITUALS_SEED.length} rituals`);
    }
  }

  findAll(eventType?: string, stateId?: number): Promise<Ritual[]> {
    const where: any = {};
    if (eventType) where.eventType = eventType;
    return this.ritualRepo.find({ where, order: { dayNumber: 'ASC' } });
  }

  findOne(id: number): Promise<Ritual> {
    return this.ritualRepo.findOne({ where: { id } });
  }

  findByEventType(type: string): Promise<Ritual[]> {
    return this.ritualRepo.find({ where: { eventType: type }, order: { dayNumber: 'ASC' } });
  }

  getEventTypes(): string[] {
    return ['wedding', 'engagement', 'childbirth', 'mundan', 'griha-pravesh', 'upanayana', 'festival'];
  }
}